### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by codypilot** [sigopsuiuc/file-sharing#20]
Make this project more accessible to new contributors by restructuring and adding context to the README

**Comment by mohammad-aliB** [comment]
@codypilot will you be doing this or is this something i can do?

**Comment by yashLadha** [comment]
@codypilot I work upon this Issue. Assign me.

**Comment by Souldiv** [comment]
#21 fixed the issue here.

**Comment by vishalpolley** [comment]
@codypilot I have cleaned the readme and also added easy accessibility features to it.
Please review my pull request. 
**Cleaned up and improved README.md** #22
